Choim err path 4modules
NEONScience/NEON-IS-data-processing pull request #229
Opened 2023-12-04 23:21 UTC by choim-sci

@covesturtevant , 

This PR is for the new  ERR_PATH to be independent of OUTPUT_DIR. It includes 4 modules, group_loader, location_loader, pub_group and pub_packager.

2024-01-09 22:41 UTC, covesturtevant requested changes
The error routing for the group loader and location loader looks good. The error routing for the pub_grouper and pub_packager is too narrow, limited to catching problems writing an output file. We need the error catching and routing to encompass much more of the code. See comments in pub_grouper.py for examples that error routing should catch.

2024-01-09 22:41 UTC, covesturtevant commented on modules/pub_grouper/pub_grouper.py
>              log.warn(f'Path {path.parent} looks to be a datum, but the directory at the group metadata index ({group_metadata_name}) does not match the expected name ({group_metadata_dir}). Skipping.
This should result in error routing

2024-01-09 22:41 UTC, covesturtevant commented on modules/pub_grouper/pub_grouper.py
>              continue
These should also result in error routing

2024-01-09 22:41 UTC, covesturtevant commented on modules/pub_grouper/pub_grouper.py
The error routing here is too narrow. Currently error routing is limited to problems writing the output file, but there are at least 3 places earlier in the code that catch problems and skip. Any place this occurs should be caught by the error routing so that these problematic datums show in the error directory.

2024-01-09 22:41 UTC, covesturtevant commented on modules/pub_packager/pub_packager.py
The error routing is too narrow. It is limited to a problem writing the manifest file, but there are numerous places where a problem may occur. I'd like to see error routing encompass much more of the code.

2024-01-24 17:03 UTC, choim-sci commented
@covesturtevant, 

The change requests are implemented in pub_grouper and pub_packager.

2024-01-24 17:21 UTC, choim-sci commented
@covesturtevant, 

I found a small bug in pub_packager.  So wait a little.

2024-01-25 18:24 UTC, choim-sci commented
@covesturtevant, 

The bug is fixed. Thanks

2024-04-16 02:04 UTC, choim-sci commented
Closing.  Open a new PR for the V2 branch

2024-04-16 02:10 UTC, choim-sci commented
closing #229, refer to a new PR, #266.

2024-04-16 02:10 UTC, closed without merging