Choim nse9957 v3
NEONScience/NEON-IS-data-processing pull request #232
Opened 2024-01-08 16:21 UTC by choim-sci

@covesturtevant , 

This PR is for group_path error routing.

2024-01-09 23:23 UTC, covesturtevant requested changes
We need the error routing cover a bit more here. Currently the error catching/routing is limited to writing the group file. It also needs to cover writing the other outputs that directly follow (lines 138-160).

2024-01-16 01:41 UTC, choim-sci commented
@covesturtevant 

CRs are implemented.

2024-01-18 17:26 UTC, covesturtevant approved these changes

2024-01-18 17:26 UTC, covesturtevant commented
Looks great. Thanks @choim-sci

2024-01-18 17:27 UTC, merged