Choim docker image testing
NEONScience/NEON-IS-data-processing pull request #332
Opened 2024-08-14 22:41 UTC by choim-sci

@covesturtevant , 

This is the implementation of the first action of the two, (Liz's doc 1-3.)  The test pipeline is  parQuantumLine_group_loader.  The files before (quay image id) and after (sha image id) are copied over here, /scratch/pfs/before-sha/par-quantum-line and /scratch/pfs/after-sha/par-quantum-line, respectively.  I compared the two. Looked correct.

FYI, The work is completed. but due to R installation failure atm, I am not able to show the whole process.  So I am checking in the first only.  Last time I ran the pipeline update with R was about 2 weeks ago. I am not sure why the R installation is failing now.

2024-08-15 16:39 UTC, covesturtevant requested changes
Looking good! A few edits requested. Please see in-line comments.

2024-08-15 16:39 UTC, covesturtevant commented on .github/workflows/DEV_group_loader.yml
> +      - "v*.*.*"
This will trigger off any git tag with a semver. We want this in the form 
```shell
group_loader/v*.*.*
```

2024-08-15 16:39 UTC, covesturtevant commented on pipe/parQuantumLine/parQuantumLine_group_loader.yaml
> +    - cd modules/
Why does it need to cd into modules? Better to have the code accessible from the working directory of the image. Looks like I missed that change to the Dockerfile - sorry for not catching it sooner. Please adjust the Dockerfile back to placing the code directly into the working directory (not nested within modules/).

2024-08-15 16:39 UTC, covesturtevant commented on pipe/parQuantumLine/parQuantumLine_group_loader.yaml
Since this is not ready for production, let's please revert this change to this specific file pipe/parQuantumLine/parQuantumLine_group_loader.yaml. Otherwise there is a risk of pushing this into production if it is merged into master. You can still test with this pipeline in pachyderm-dev, but copy the pipeline file over to a testing directory such as /pipe/sandbox/parQuantumLine_group_loader.yaml so that Github actions will not trigger an update to Pachyderm.

2024-08-22 15:16 UTC, choim-sci commented on pipe/parQuantumLine/parQuantumLine_group_loader.yaml
@covesturtevant, 

The Dockerfiles were restored, and so was parQuantumLine_group_loader.yaml. 
Tested.

2024-08-28 15:25 UTC, choim-sci commented on pipe/parQuantumLine/parQuantumLine_group_loader.yaml
Hi @covesturtevant, 

The change requests were implemented.  Let me know if anything missing, I can do a demo to refresh.

2024-09-05 20:33 UTC, choim-sci commented
@covesturtevant 

closing this, and opening a new one, #342.

2024-09-05 20:33 UTC, closed without merging