Choim nse10541 10682 v2
NEONScience/NEON-IS-data-processing pull request #342
Opened 2024-09-05 20:32 UTC by choim-sci

@covesturtevant, 

This has the change request from PR332, 
 https://github.com/NEONScience/NEON-IS-data-processing/pull/332
and adding actions for get changed files and update pipelines.  

Closing PR332.

2024-09-12 20:54 UTC, covesturtevant requested changes
See comments. Thanks!

2024-09-12 20:54 UTC, covesturtevant commented on .github/workflows/DEV_location_loader.yml
> +name: "DEV-location-loader"
Naming convention:
build-push workflow yamls: build_push_<image name>.yaml
build-push-update workflow yamls: build_push_update_<image name>.yaml

2024-09-12 20:54 UTC, covesturtevant commented on .github/actions/build-push/action.yml
> +              type=ref,event=pr
Please comment this line. Not needed (for now)

2024-09-12 20:54 UTC, covesturtevant commented on .github/actions/build-push/action.yml
> +              ${{ env.GCP_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.semver }}
Comment this line

2024-09-12 20:54 UTC, covesturtevant commented on .github/workflows/DEV_group_loader.yml
Please delete. Test only with errored_datums_reader and processed_datums_reader (use new "neon-is-...) convention when creating image registry in GCP.

2024-09-12 20:54 UTC, covesturtevant commented on .github/workflows/DEV_location_loader.yml
Please delete. Test only with errored_datums_reader and processed_datums_reader (use new "neon-is-...) convention when creating image registry in GCP.

2024-09-12 20:54 UTC, covesturtevant commented on .github/workflows/neon-is-group-loader.yml
Test only with errored_datums_reader and processed_datums_reader (use new "neon-is-...) convention when creating image registry in GCP.

2024-09-12 20:54 UTC, covesturtevant commented on .github/workflows/neon-is-location-loader.yml
Test only with errored_datums_reader and processed_datums_reader (use new "neon-is-...) convention when creating image registry in GCP.

2024-09-12 21:52 UTC, choim-sci commented
@covesturtevant, 
The change requests implemented are below: 
1) *loader.ymls deleted;
2) build-push.yml and build-push-update.yml added
3) for build-push-update: "with image-tag" from wf yml and "inputs" from the action commented to show the push with semantic version clearly
4) for build-push: push with semver tag commented from build-push action to show the push with short-sha

2024-09-13 00:19 UTC, covesturtevant approved these changes

2024-09-13 00:19 UTC, covesturtevant commented on .github/workflows/build_push.yml
>    IMAGE_NAME: neon-is-group-loader
please change image to neon-is-errored-datums-reader (will required creating this image in the Google artifact registry)

2024-09-13 00:20 UTC, merged